version: '3.9'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo_security
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - dusty-java-postgresql-data:/var/lib/postgresql/data
    restart: always  # unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
    networks:
      - dev-backend

  backend:
    container_name: dusty-demo_security
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_security
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dusty/demo_security
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev-backend

volumes:
  dusty-java-postgresql-data: {}
  logs:
    driver: local

networks:
  dev-backend:
    name: dev-backend
#    driver: bridge
